def build(bld):
    obj = bld.create_ns3_program('vanet-simulation',
                                ['core', 'mobility', 'wifi', 'internet', 'applications', 'vanet'])
    obj.source = 'vanet-simulation.cc'
